"""Qazterion Core Package.

Modular components for classification, planning, execution, review, and git operations.
"""

from qz_core.client import client, PROXY_URL, MASTER_KEY, get_client
from qz_core.common import _persist_task
from qz_core.classifier import (
    COMPLEXITY_MODEL_MAP,
    FORCED_TASK_MODE,
    PLAN_APPROVAL_SETTING,
    TASK_MODES,
    _COMPLEX_KEYWORDS,
    _QUICK_KEYWORDS,
    _VALID_APPROVAL_SETTINGS,
    _heuristic_task_mode,
    classify_task_complexity,
    classify_task_mode,
)
from qz_core.planner import (
    PLANNER_MODEL,
    SUBTASK_DAG_SYSTEM_PROMPT,
    ask_clarifying_questions,
    call_architect,
    call_planner,
    convert_plan_to_subtasks,
    format_clarifications,
    generate_clarifying_questions,
    prompt_plan_approval,
    requires_plan_approval,
    resolve_plan,
    validate_subtask_dag,
    _parse_subtasks_json,
)
from qz_core.reviewer import self_review
from qz_core.git_ops import (
    generate_commit_message,
    _commit_hash_from_result,
    get_current_head,
    get_uncommitted_files,
    is_worktree_clean,
    commit_exists,
)
from qz_core.executor import (
    EXECUTOR_FALLBACKS,
    FAILURE_MARKERS,
    MAX_HISTORY_MESSAGES,
    MODEL_REQUEST_ATTEMPTS,
    RECENT_HISTORY_MESSAGES,
    SYSTEM_PROMPT,
    USAGE_TRACKER,
    TestBaseline,
    _history_for_summary,
    _is_test_file_path,
    _provider_failure_kind,
    _recent_exchange_start,
    _task_requires_test_changes,
    _test_failure_signature,
    _tool_result_failed,
    capture_pre_existing_test_failures,
    request_completion,
    roll_conversation_summary,
    run_executor,
)
from qz_core.dag_executor import (
    HardDAGExecutor,
    NodeResult,
    DAGExecutionResult,
)
from qz_router import select_route
from qz_validation import ValidationPipeline, ValidationReport, CheckResult, CheckStatus
from qz_recovery import (
    ResumeManager,
    ResumePlan,
    IntegrityResult,
    IntegrityStatus,
    ResumeOutcome,
    get_resume_manager,
)

__all__ = [
    "client",
    "PROXY_URL",
    "MASTER_KEY",
    "get_client",
    "_persist_task",
    "COMPLEXITY_MODEL_MAP",
    "FORCED_TASK_MODE",
    "PLAN_APPROVAL_SETTING",
    "TASK_MODES",
    "_COMPLEX_KEYWORDS",
    "_QUICK_KEYWORDS",
    "_VALID_APPROVAL_SETTINGS",
    "_heuristic_task_mode",
    "classify_task_complexity",
    "classify_task_mode",
    "PLANNER_MODEL",
    "SUBTASK_DAG_SYSTEM_PROMPT",
    "ask_clarifying_questions",
    "call_architect",
    "call_planner",
    "convert_plan_to_subtasks",
    "format_clarifications",
    "generate_clarifying_questions",
    "prompt_plan_approval",
    "requires_plan_approval",
    "resolve_plan",
    "validate_subtask_dag",
    "_parse_subtasks_json",
    "self_review",
    "generate_commit_message",
    "_commit_hash_from_result",
    "EXECUTOR_FALLBACKS",
    "FAILURE_MARKERS",
    "MAX_HISTORY_MESSAGES",
    "MODEL_REQUEST_ATTEMPTS",
    "RECENT_HISTORY_MESSAGES",
    "SYSTEM_PROMPT",
    "USAGE_TRACKER",
    "TestBaseline",
    "_history_for_summary",
    "_is_test_file_path",
    "_provider_failure_kind",
    "_recent_exchange_start",
    "_task_requires_test_changes",
    "_test_failure_signature",
    "_tool_result_failed",
    "capture_pre_existing_test_failures",
    "request_completion",
    "roll_conversation_summary",
    "run_executor",
    "HardDAGExecutor",
    "NodeResult",
    "DAGExecutionResult",
    "select_route",
    "ValidationPipeline",
    "ValidationReport",
    "CheckResult",
    "CheckStatus",
    "ResumeManager",
    "ResumePlan",
    "IntegrityResult",
    "IntegrityStatus",
    "ResumeOutcome",
    "get_resume_manager",
]
